spring:
  application:
    name: api-gateway

      ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        ## PET SERVICE
      - id: pet-service
        uri: lb://pet-service
        predicates:
          - Path=/api/**
        filters:
          - StripPrefix=1


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
